### PR TITLE
Exclude useless files from npm package

### PR DESCRIPTION
**Pull request by domenic**
Nobody wants your Makefile or component stuff

### CODE REVIEW

**Comment by dougwilson** [comment]
@tj can you add myself (dougwilson) or @jonathanong to the module on `npm` to publish a few minor things like this, please :)?

**Comment by dougwilson** [comment]
Ping @tj ;)

> @tj can you add myself (dougwilson) or @jonathanong to this module on npm ("escape-html") to publish a few minor things like this, please :)?

**Comment by dougwilson** [comment]
Ping @tj ;)

> @tj can you add myself (dougwilson) or @jonathanong to this module on npm ("escape-html") to publish a few minor things like this, please :)?

**Comment by dougwilson** [comment]
Ping @tj ;)

> @tj can you add myself (dougwilson) or @jonathanong to this module on npm ("escape-html") to publish a few minor things like this, please :)?

**Comment by tj** [comment]
hey sorry, added!

**Comment by dougwilson** [comment]
Thanks, @tj :) @domenic this has been published as 1.0.2

**Pull request closed without merging**
